### ISSUE TITLE
this app crashes when using the rossman feature if there is no internet connection after writing multiple letters

### ISSUE THREAD

**Issue by muhammadarif1** [zouroboros/filmchecker#11]
EXPECTED BEHAVIOR
should be when user wants to update movie files user can update it easily.

ACTUAL BEHAVIOR
when users update movie files, but users do not have a network connection and after the user wrote some letters, this application crashes and can no longer be opened

HOW TO REPRODUCE
DOWNLOAD FILM CHEKER APP FROM F-DROID OR PLAYSTORE
LAUCH THE APP
TURN OFF YOUR DATA CONNECTION
CLICK ON+ OPTION
CHOSEROSSMAN FEATURE
TYPE SOME LETTER AND NOTE THE BUG
BROWSER = FILM CHEKER V 1.4.1.0
DEVICE = ANDROId 6.0

```Process: me.murks.filmchecker, PID: 10476
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
    at me.murks.filmchecker.background.RmLoadStoresTask.onPostExecute(RmLoadStoresTask.java:50)
    at me.murks.filmchecker.background.RmLoadStoresTask.onPostExecute(RmLoadStoresTask.java:20)
    at android.os.AsyncTask.finish(AsyncTask.java:636)
    at android.os.AsyncTask.access$500(AsyncTask.java:177)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5376)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:947)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)```

**Comment by zouroboros** [comment]
Thanks for reporting the bug, I will have a look into it.

FYI, the app is intended for checking film (as in analog film) development orders not movies.

**Comment by zouroboros** [comment]
The new version 1.4.2 with the bug fix should be in f-droid in a week or so
